export type LeadStatus = "lead" | "warm" | "hot" | "meeting_schedule" | "meeting_done"

// Simplified color scheme - one color per column
export const columnColors = {
  solution: "bg-amber-600 text-purple-50 hover:bg-amber-700 border-amber-700",
  geo: "bg-blue-600 text-purple-50 hover:bg-blue-700 border-blue-700",
  sdrOwner: "bg-purple-600 text-purple-50 hover:bg-purple-700 border-purple-700",
}

export interface Lead {
  id: string
  companyName: string
  personName: string
  position: string
  leadDate: string
  leadStatus: LeadStatus
  solution: string
  geo: string
  meetingDate: string
  sdrOwner: string
  notes: string
  personLinkedin: string
  companyWebsite: string
  companyLinkedin: string
  email: string
  phone: string
  leadRating: number
}

export const leadsData: Lead[] = [
  {
    id: "1",
    companyName: "Company XYZ",
    personName: "Alex",
    position: "CEO",
    leadDate: "May 19, 2025",
    leadStatus: "lead",
    solution: "GRC",
    geo: "Saudi",
    meetingDate: "May 22, 2025",
    sdrOwner: "SDR 3",
    notes: "Initial contact made via conference",
    personLinkedin: "",
    companyWebsite: "",
    companyLinkedin: "",
    email: "",
    phone: "",
    leadRating: 5,
  },
  {
    id: "2",
    companyName: "Tech Innovations",
    personName: "Sarah Johnson",
    position: "CTO",
    leadDate: "May 15, 2025",
    leadStatus: "warm",
    solution: "VAPT",
    geo: "UAE",
    meetingDate: "May 25, 2025",
    sdrOwner: "SDR 1",
    notes: "Interested in cloud migration solutions",
    personLinkedin: "linkedin.com/in/sarahjohnson",
    companyWebsite: "techinnovations.com",
    companyLinkedin: "linkedin.com/company/techinnovations",
    email: "sarah@techinnovations.com",
    phone: "+971 50 123 4567",
    leadRating: 4,
  },
  {
    id: "3",
    companyName: "Global Finance",
    personName: "Mohammed Al-Farsi",
    position: "CFO",
    leadDate: "May 10, 2025",
    leadStatus: "hot",
    solution: "CISOasaService",
    geo: "Kuwait",
    meetingDate: "May 30, 2025",
    sdrOwner: "SDR 2",
    notes: "Looking for financial compliance solutions",
    personLinkedin: "linkedin.com/in/mohammedalfarsi",
    companyWebsite: "globalfinance.com",
    companyLinkedin: "",
    email: "m.alfarsi@globalfinance.com",
    phone: "+974 3456 7890",
    leadRating: 3,
  },
  {
    id: "4",
    companyName: "Desert Holdings",
    personName: "Fatima Al-Mansouri",
    position: "COO",
    leadDate: "May 5, 2025",
    leadStatus: "meeting_schedule",
    solution: "GRC",
    geo: "Saudi",
    meetingDate: "May 20, 2025",
    sdrOwner: "SDR 3",
    notes: "Expanding operations, needs compliance solutions",
    personLinkedin: "linkedin.com/in/fatimamansouri",
    companyWebsite: "desertholdings.sa",
    companyLinkedin: "linkedin.com/company/desertholdings",
    email: "f.almansouri@desertholdings.sa",
    phone: "+966 54 789 0123",
    leadRating: 5,
  },
  {
    id: "5",
    companyName: "Oasis Telecom",
    personName: "Khalid Rahman",
    position: "CIO",
    leadDate: "May 3, 2025",
    leadStatus: "lead",
    solution: "VAPT",
    geo: "UAE",
    meetingDate: "May 18, 2025",
    sdrOwner: "SDR 1",
    notes: "Concerned about cybersecurity threats",
    personLinkedin: "",
    companyWebsite: "oasistelecom.bh",
    companyLinkedin: "",
    email: "k.rahman@oasistelecom.bh",
    phone: "+973 1700 1234",
    leadRating: 4,
  },
  {
    id: "6",
    companyName: "Pearl Investments",
    personName: "Layla Al-Thani",
    position: "Managing Director",
    leadDate: "April 28, 2025",
    leadStatus: "warm",
    solution: "CISOasaService",
    geo: "Kuwait",
    meetingDate: "May 15, 2025",
    sdrOwner: "SDR 2",
    notes: "Interested in investment analytics platform",
    personLinkedin: "linkedin.com/in/laylaalthani",
    companyWebsite: "pearlinvestments.qa",
    companyLinkedin: "linkedin.com/company/pearlinvestments",
    email: "l.althani@pearlinvestments.qa",
    phone: "+974 5567 8901",
    leadRating: 5,
  },
  {
    id: "7",
    companyName: "Falcon Security",
    personName: "Omar Al-Suwaidi",
    position: "CEO",
    leadDate: "April 25, 2025",
    leadStatus: "hot",
    solution: "VAPT",
    geo: "UAE",
    meetingDate: "May 12, 2025",
    sdrOwner: "SDR 1",
    notes: "Looking to partner on government security projects",
    personLinkedin: "linkedin.com/in/omaralsuwaidi",
    companyWebsite: "falconsecurity.ae",
    companyLinkedin: "linkedin.com/company/falconsecurity",
    email: "omar@falconsecurity.ae",
    phone: "+971 50 987 6543",
    leadRating: 4,
  },
  {
    id: "8",
    companyName: "Royal Petroleum",
    personName: "Abdullah Al-Saud",
    position: "Director of IT",
    leadDate: "April 20, 2025",
    leadStatus: "meeting_done",
    solution: "GRC",
    geo: "Saudi",
    meetingDate: "May 8, 2025",
    sdrOwner: "SDR 3",
    notes: "Needs regulatory compliance solutions for energy sector",
    personLinkedin: "linkedin.com/in/abdullahalsaud",
    companyWebsite: "royalpetroleum.sa",
    companyLinkedin: "linkedin.com/company/royalpetroleum",
    email: "a.alsaud@royalpetroleum.sa",
    phone: "+966 55 123 4567",
    leadRating: 5,
  },
  {
    id: "9",
    companyName: "Marina Developments",
    personName: "Noor Al-Khalifa",
    position: "Head of Operations",
    leadDate: "April 15, 2025",
    leadStatus: "lead",
    solution: "CISOasaService",
    geo: "Kuwait",
    meetingDate: "May 5, 2025",
    sdrOwner: "SDR 2",
    notes: "Interested in digital transformation for property management",
    personLinkedin: "linkedin.com/in/nooralkhalifa",
    companyWebsite: "marinadevelopments.bh",
    companyLinkedin: "",
    email: "n.alkhalifa@marinadevelopments.bh",
    phone: "+973 1700 5678",
    leadRating: 3,
  },
  {
    id: "10",
    companyName: "Crescent Healthcare",
    personName: "Aisha Al-Jabri",
    position: "CTO",
    leadDate: "April 10, 2025",
    leadStatus: "meeting_schedule",
    solution: "VAPT",
    geo: "Saudi",
    meetingDate: "May 3, 2025",
    sdrOwner: "SDR 3",
    notes: "Needs healthcare data security solutions",
    personLinkedin: "linkedin.com/in/aishajabri",
    companyWebsite: "crescenthealthcare.om",
    companyLinkedin: "linkedin.com/company/crescenthealthcare",
    email: "a.jabri@crescenthealthcare.om",
    phone: "+968 9123 4567",
    leadRating: 4,
  },
]
